ebi-webcomponents/nightingale

- app/package.json
- app/src/App.jsx
- app/src/components/Playground.jsx
- app/src/components/examples.js
- app/webpack.common.js
Adding a playground area on the showcase app.
It uses React Hooks + Suspense.
@xwatkins If you approve the PR, please deploy it in GH pages
> Playground

- app/src/components/ProtvistaManager.jsx
- packages/protvista-zoom-tool/package.json
- packages/protvista-zoom-tool/src/ProtvistaZoomTool.js
- packages/protvista-zoom-tool/src/index.js
Package 'protvista-zoom-tool' is created. By default , two buttons '+' and '-' are shown. They are  also customisable
> Zoom using buttons

- packages/protvista-variation-graph/src/protvista-variation-graph.js
none
Fix off-by-one issue and optimise code in variation-graph
> Variation graph fix

- app/src/components/ProtvistaTooltip.jsx
- packages/protvista-tooltip/README.md
- packages/protvista-tooltip/src/protvista-tooltip.js
Radical changes to the tooltip component:
- Auto-positions itself depending on available space, even if content changes
- More stylable through custom properties (documented)
- Controlable through more properties
> better tooltip, improved logic and API

- app/src/App.jsx
- app/src/components/TextareaSequence.jsx
- app/webpack.common.js
- package.json
- packages/textarea-sequence/README.md
- packages/textarea-sequence/package.json
- packages/textarea-sequence/src/Quill.js
- packages/textarea-sequence/src/TextareaSequence.js
- packages/textarea-sequence/src/defaults.js
- packages/textarea-sequence/src/index.js
- packages/textarea-sequence/src/quill.test.js
- webpack.config.js
- yarn.lock
N/A
Adding a new component:  `<textarea-sequence />`
The readme of the component describes its parameters and methods.
I published on a canary version and you can play with a demo here: https://codepen.io/gustavo-salazar/full/PoZwNwJ
**Note:** I changed a bit the configuration of typescript in webpack, from `babel-typescript` plugin to `ts-loader` webpack loader. I checked `data-loader` in the example app and seems to be OK. But please check yourselves.
I haven't added test to this package (I should). But existing tests are passing
> Textarea sequence

- packages/protvista-track/src/DefaultLayout.js
- packages/protvista-track/src/protvista-track.js
The DefaultLayout was not vertically centering the track contents. This is a small PR but could have knock-on effect on your components.
Establish the correct yPosition based on feature height and track height.
> Fix centering issue

- app/src/components/ProtvistaMSA.jsx
- packages/protvista-msa/README.md
- packages/protvista-msa/src/ProtvistaMSA.js
- packages/textarea-sequence/src/quill.test.js
https://www.ebi.ac.uk/panda/jira/browse/TRM-24473
- Now can pass custom elements as `label` to the ProtvistaMSA
- Added `activeLabel` attribute
- Added `onActiveTrackChange` property
> Active sequence label and callback function on change

- app/src/components/ProtvistaManager.jsx
- lerna.json
- packages/protvista-manager/README.md
- packages/protvista-manager/src/protvista-manager.js
- packages/protvista-msa/src/ProtvistaMSA.js
Added some of the common attributes as observed attributes so they can be initialised and updated directly on the component.
> Manager attributes

- app/src/components/ProtvistaMSA.jsx
- packages/protvista-msa/src/ProtvistaMSA.js
**Depends on https://github.com/ebi-webcomponents/react-msa-viewer/pull/4**
- Allows consumers:
- Display coordinates on left/right for each sequence in MSA.
- Offset by sequence start (if provided).
- Created addGaps for MSA storybook.
> Use coordinates in MSA. Create addGap fn.

- packages/protvista-variation-adapter/src/protvista-variation-adapter.ts
- packages/protvista-variation-adapter/test/__snapshots__/ProtvistaVariationAdapter.spec.js.snap
> Define transformed type

- packages/protvista-datatable/jest.config.json
- packages/protvista-datatable/package.json
- packages/protvista-datatable/src/protvista-datatable.js
- packages/protvista-datatable/tests/mockData/columnConfig.js
- packages/protvista-datatable/tests/mockData/data.json
- packages/protvista-datatable/tests/protvista-datatable.test.js
- yarn.lock
> Add example component test for datatable

- packages/protvista-utils/src/Region.js
- packages/protvista-utils/src/TrackHighlighter.js
- packages/protvista-utils/src/__snapshots__/region.test.js.snap
- packages/protvista-utils/src/region.test.js
- packages/protvista-zoomable/src/protvista-zoomable.js
I'm working on a new version of [MolArt](https://github.com/scheuerv/typed-molart) and I need to have highlights of different colors for better visualization, so I propose the following improvement.
> Extended highlighting capability (color)

- app/src/components/ProtvistaSequence.jsx
- app/src/components/examples.js
- packages/protvista-sequence/README.md
- packages/protvista-sequence/src/protvista-sequence.js
Adds a new attribute to protvista-sequence to configure the number of ticks.
> Configurable number of ticks in protvista-sequence

- app/src/App.css
- app/src/App.jsx
- app/src/components/NightingaleSunburst.jsx
- packages/nightingale-sunburst/README.md
- packages/nightingale-sunburst/package.json
- packages/nightingale-sunburst/src/index.js
- packages/nightingale-sunburst/src/nightingale-sunburst.js
- packages/protvista-tooltip/src/protvista-tooltip.js
New component `nightingale-sunburst` to display taxonomies
> Taxonomy sunburst

- packages/protvista-structure/src/protvista-structure.ts
> Add missing height setter in protvista-structure

- app/src/components/ProtvistaStructure.jsx
- packages/protvista-structure/package.json
- packages/protvista-structure/src/__test__/__mocks__/mapping-test-cases.js
- packages/protvista-structure/src/__test__/__mocks__/mappings.js
- packages/protvista-structure/src/__test__/position-mapping.test.js
- packages/protvista-structure/src/position-mapping.ts
- packages/protvista-structure/src/protvista-structure.ts
- packages/protvista-structure/src/structure-viewer.ts
See https://github.com/ebi-webcomponents/nightingale/issues/206
- Add support for selecting a range across mapping regions (across gaps in mapping)
- Make sure that only chains present in mapping are highlighted
See comments in code for more context
> Add support for mapping with gaps and different chains

- packages/protvista-datatable/README.md
- packages/protvista-datatable/src/protvista-datatable.ts
- packages/protvista-overlay/src/ProtvistaOverlay.js
Toggle Datatable to expand and collapse
Based on the expandTable property, the height style is set.
> Datatable expansion

- packages/nightingale-coloured-sequence/src/nightingale-coloured-sequence.ts
- packages/nightingale-interpro-track/src/nightingale-interpro-track.ts
- packages/nightingale-linegraph-track/src/nightingale-linegraph-track.ts
- packages/nightingale-new-core/src/withMargin.ts
- packages/nightingale-sequence/src/nightingale-sequence.ts
- packages/nightingale-track/src/nightingale-track.ts
> Updated some components to enable dynamic change

- README.md
Had to do this to get the storybook working for me otherwise I encountered TS errors.
> README: add build to locally showcase application

- lerna.json
- packages/nightingale-coloured-sequence/package.json
- packages/nightingale-links/package.json
- packages/nightingale-msa/package.json
- packages/nightingale-sequence/package.json
- packages/nightingale-sequence/tests/nightingale-sequence.test.js
- packages/nightingale-sunburst/README.md
- packages/nightingale-sunburst/package.json
- packages/nightingale-sunburst/src/index.ts
- packages/nightingale-sunburst/src/nightingale-sunburst.ts
- packages/nightingale-sunburst/test/__snapshots__/nightingale-sunburst.test.ts.snap
- packages/nightingale-sunburst/test/nightingale-sunburst.test.ts
- packages/nightingale-sunburst/test/taxonomy.min.json
- stories/12.Sunburst/NightingaleSunburst.stories.mdx
- stories/12.Sunburst/NightingaleSunburst.stories.ts
Migration `nightingale-sunburst` to TS. It was already using Lit!
**Note:** Check after #238
> Nightingale sunburst

- packages/nightingale-msa/src/components/Canvas/SequenceViewer.ts
- packages/nightingale-msa/src/nightingale-msa.ts
- stories/10.MSA/NightingaleMSA.stories.ts
- Expose the setting of features for nightingale-msa
- Add story showing features and an event listener for clicks
> MSA features

- packages/nightingale-structure/src/index.ts
quick fix for issue 291
closes #291
> replace Sequence with Structure #291

- dev/index.html
- packages/nightingale-sequence-heatmap/README.md
- packages/nightingale-sequence-heatmap/package.json
- packages/nightingale-sequence-heatmap/src/nightingale-sequence-heatmap.ts
- packages/nightingale-sequence-heatmap/tests/__snapshots__/nightingale-sequence-heatmap.test.js.snap
- yarn.lock
Hello. The PDBe heatmap-component has been recently updated to it’s first stable version (1.0) and I’ve been asked to update the Nightingale Sequence Heatmap component to reflect this.
These are mostly minor fixes that do not affect what was previously discussed and adjusted in the first PR.
Perhaps the biggest change is the introduction of an attributed named "hm-highlight-width" to control the border width of the heatmap highlight.
Please let me know if there is anything requiring adjustment and I will be glad to reply and fix it
> Nightingale sequence heatmap update to v1

- packages/nightingale-new-core/src/mixins/withResizable/index.ts
Reverts ebi-webcomponents/nightingale#304
> Revert "Improve resize performance"

- packages/nightingale-track/README.md
- packages/nightingale-track/src/FeatureShape.ts
- packages/nightingale-track/tests/mockData/data.json
- stories/05.Track/NightingaleTrack.stories.ts
This PR adds two new shapes for `nightingale-track`: `tag` and `doubleEndedTag`.
> Tag shapes

- packages/nightingale-structure/src/nightingale-structure.ts
On clicking on the structure, the tooltip wasn't showing as expected. It if fixed and customised to show the position in the protein sequence along with the structure related info.
> Fix Molstar tooltip
