ebi-webcomponents/nightingale

packages/protvista-zoomable/src/protvista-zoomable.js
Some users have requested to be able to select multiple features. This is especially useful when looking at variants and the 3D structure together.
When Shift is pressed, if another feature/variant is clicked, its coordinates will be added to the list of coordinates for highlight. Clicking away or on another feature (with shift released) will reset that selection.
=> Handle multiselect

packages/protvista-structure/src/protvista-structure.js
Users have requested being able to select residues in LiteMol and see the corresponding positions in protvista tracks.
Intercept the click event on molecule to submit a "change" event. Translate positions between residues and uniprot sequence before doing so.
=> Add highlight event from structure

app/src/components/ProtvistaNavigation.jsx, lerna.json, packages/protvista-navigation/README.md, packages/protvista-navigation/src/protvista-navigation.js
Allow `protvista-navigation` consumer to offset navigation start/end points with `rulerstart` attribute
=> Add rulerstart as attribute to protvista-navigation.

packages/protvista-manager/src/protvista-manager.js
Some attributes were set to `"null"`. 
The most common example is the highlight in https://ebi-webcomponents.github.io/nightingale/#/manager if you mouse over any feature and then mouse out, you will see that all the tracks will have the attribute `highlight="null"`.
This is causing some issues in the InterPro website
Just a one-liner to `removeAttribute` in case is null
=> removing attributes instead of "null"

packages/protvista-manager/src/protvista-manager.js
Since adding the "default" observed attributes, adding a custom attribute didn't work anymore
Re-initialise the array of `attributeValues` when the "attributes" attribute changes.
=> Actually update attributes

packages/protvista-track/src/protvista-track.js
The event is triggered on hovering over the feature shape. In cases like helix, or other shapes different than rectangle, it causes the event to trigger every time the mouse pointer moves between the path resulting in flickering like in https://github.com/ProteinsWebTeam/interpro7-client/issues/242
An extra group is added `<g class="fragment-group"><path /><rect /></g>` in place of just the `<path>` and the rectangle is  responsible for event handling.
Could you please let us know if the above change is okay and goes well at your end?
=> Protvista track feature improvement

packages/protvista-navigation/package.json, packages/protvista-navigation/src/protvista-navigation.js, packages/protvista-utils/README.md, packages/protvista-utils/src/index.js, packages/protvista-utils/src/withMargin.js, packages/protvista-zoomable/src/protvista-zoomable.js
FIX #109 
It creates a higher order component that embeds the logic for a margin object. it exposes the following attributes and parameters:
* `marginleft`
* `marginright`
* `margintop`
* `marginbottom`
=> adding a higher order component withMargin

app/src/components/ProtvistaManager.jsx, packages/protvista-zoom-tool/src/ProtvistaZoomTool.js
#128 
- For the content of `<button/>`, change to using slots
- css to reset the button styling and apply default styles, and expose some properties through css variables
- Add an option (through a slot) to provide an extra button to zoom in right to the sequence level (30 amino acids)
- Refactor the zooming logic to only move the `end` unless it's reached the full length
These changes will have implications with InterPro's use of the component @Swaathik @gustavo-salazar
=> Use slots and css variables

app/src/App.jsx, app/src/components/NightingaleLineGraphTrack.jsx, app/src/components/ProtvistaManager.jsx, app/src/mocks/line-graph-chart.json, packages/nightingale-linegraph-track/README.md, packages/nightingale-linegraph-track/mock/data.json, packages/nightingale-linegraph-track/package.json, packages/nightingale-linegraph-track/src/index.js, packages/nightingale-linegraph-track/src/nightingale-linegraph-track.js, packages/protvista-variation-graph/mock/data.json
Replacement for Protvista-variation-graph for it to be more generic
- It accepts multiple charts
- Colour customisation. If not specified, d3 colour scale is used.
- Range of min-max values. 
- Allow the use of the (or some of the) different line curve types defined in the D3 API (https://github.com/d3/d3-shape/blob/v2.0.0/README.md#curves)
- Allow selection of a data point.
=> Nightingale linegraph track

packages/protvista-variation-adapter/src/tooltipGenerators.ts, packages/protvista-variation-adapter/src/variants.ts, packages/protvista-variation-adapter/test/ProtvistaVariationAdapter.spec.js, packages/protvista-variation-adapter/test/__snapshots__/ProtvistaVariationAdapter.spec.js.snap, packages/protvista-variation-adapter/test/variants.json
Some variants now have extra information allowing to link to Ensembl COVID-19. This should be displayed in the tooltip.
Add logic to extract the corresponding id and generate the link.
=> Add support for Ensembl COVID-19 links

app/src/mocks/line-graph-chart.json, packages/nightingale-linegraph-track/README.md, packages/nightingale-linegraph-track/src/nightingale-linegraph-track.js
Use `fill: true` in line plot to produce a filled area chart
Implements https://github.com/ebi-webcomponents/nightingale/issues/149
=> Filled area chart using "area" field in line plot

app/src/components/TextareaSequence.jsx, packages/textarea-sequence/README.md, packages/textarea-sequence/src/Quill.js, packages/textarea-sequence/src/TextareaSequence.js, packages/textarea-sequence/src/defaults.js, packages/textarea-sequence/src/quill.test.js
Adding the attribute `disable-header-check` to the `textarea-sequence` component. So it is possible to clean up a single sequence without adding the generated header.
=> sequence-textarea: disable-header-check

packages/protvista-structure/src/protvista-structure.ts
This was an oversight on the original PR related to #202.
=> Remove return type annotation on protvista-structure height setter

packages/protvista-structure/src/__test__/__mocks__/mapping-test-cases.js, packages/protvista-structure/src/__test__/__mocks__/mappings.js, packages/protvista-structure/src/position-mapping.ts
Turns out that trying to select a region across two chains already shows an error "Start or end coordinate outside of mapping range". This is because the mappings are processed separately for each chain:
https://github.com/ebi-webcomponents/nightingale/blob/master/packages/protvista-structure/src/position-mapping.ts#L55-L61
I added a test case demonstrating this behavior.
=> Add test case for structure mapping between chains

app/src/components/ProtvistaStructure.jsx, packages/protvista-structure/README.md, packages/protvista-structure/src/protvista-structure.ts, packages/protvista-structure/src/structure-viewer.ts
https://github.com/ebi-webcomponents/nightingale/issues/216
- Added support for `use-ctrl-to-zoom` attribute to protvista-structure 
- When enabled, molstar zoom binding is configured to require ctrl key to be pressed. Molstar documentation then shows this in Controls info window
- Added example to gallery
=> Add use-ctrl-to-zoom for protvista-structure

packages/nightingale-sequence/src/nightingale-sequence.ts
A rounding error for D3 Axes in [nightingale-sequence](https://github.com/ebi-webcomponents/nightingale/blob/8d22e6c4027a6b9c693c5683ca386d3c309494aa/packages/nightingale-sequence/src/nightingale-sequence.ts#L195-L200) caused the starting tick to disappear if width/length was modified to certain values.
[The xScale for the axis object is copied and its domain is rounded as decimal numbers are irrelevant for D3 Axes.](https://github.com/Two-Kay/nightingale/blob/267a2541507d1ef917a8f5ce3df9b968e06450db/packages/nightingale-sequence/src/nightingale-sequence.ts#L196-L198)
=> Fix for issue with disappearing D3 axis tick in sequences

packages/nightingale-sequence/src/nightingale-sequence.ts
While the rounding fixes the missing ticks on the sole sequence component without causing any further issues while isolated, I did notice it causes issues in the manager component since it affects the exact position of a tick there as the sequence doesn't have to start or end at a rounded number.
Only in its isolated state when using an integer starting point, the floating point error will become noticeable.
=> Revert rounding of xAxis

packages/protvista-structure/src/structure-viewer.ts
In our app I discovered that there are race conditions with configuring the structure viewer.
In StructureViewer constructor, this line sometimes fails because the molstar plugin has not been initialized yet:
https://github.com/ebi-webcomponents/nightingale/blob/v3/packages/protvista-structure/src/structure-viewer.ts#L139-L140
This PR solves this by wrapping that piece of code into a callback that's executed when molstar canvas is initialized.
=> Handle async init of molstar

packages/nightingale-saver/README.md, packages/nightingale-saver/src/nightingale-saver.ts, stories/08.Saver/NightingaleSaver.stories.ts
The size of the canvas (on which the image is drawn before being downloaded) is defined as such:
https://github.com/ebi-webcomponents/nightingale/blob/d77b9f52af3e3182a5bd92023ee06135a46f2452/packages/nightingale-saver/src/nightingale-saver.ts#L52
However, when `debug` is `true`, the canvas is added to `element`:
https://github.com/ebi-webcomponents/nightingale/blob/d77b9f52af3e3182a5bd92023ee06135a46f2452/packages/nightingale-saver/src/nightingale-saver.ts#L66
This results in `element` being higher and higher, and the downloaded image as well.
This PR fixes this by storing the initial height/width of `element` in private features.
Three other changes:
- rename `debug` with `preview`
- add the `preview` option to the `nightingale-saver`'s story in storybook
- when `preview` is `true`, …
=> Minor fix in nightingale-saver

packages/nightingale-new-core/src/mixins/withResizable/index.ts
This improves performance of `withResizable` by removing Forced reflow, and decreases initial load time when many tracks are present.
=> Improve resize performance

packages/nightingale-interpro-track/src/nightingale-interpro-track.ts, packages/nightingale-track-canvas/src/nightingale-track-canvas.ts, packages/nightingale-track/src/config.ts, packages/nightingale-track/src/nightingale-track.ts, stories/18.NightingaleTrackCanvas/NightingaleTrackCanvas.stories.ts
Include logic to highlight residues present in a feature for Canvas track which was present in Nightingale-track. 
Convert feature.start and feature.end to Number while calculating fragmentLength as it was giving long numbers from String concatenation sometimes.
=> Adaptation of canvas-track

packages/nightingale-sequence-heatmap/README.md, packages/nightingale-sequence-heatmap/package.json, packages/nightingale-sequence-heatmap/src/heatmap-component.css.ts, packages/nightingale-sequence-heatmap/src/nightingale-sequence-heatmap.ts, yarn.lock
This PR fixes a bug with NightingaleSequenceHeatmap resizing, which was causing misaligned highlights.
I also changed the default heatmap color scheme to white-yellow-green (YlGn from ColorBrewer).
To apply AlphaMissense coloring, follow the [example](https://github.com/midlik/nightingale/blob/heatmap-scale-fix/packages/nightingale-sequence-heatmap/README.md#setcolord-hotmapdata--) provided in README.md.
=> Heatmap scale fix
